name: Publish Docker Image

on:
  # 自动触发：当有新的tag被push时
  push:
    tags:
      - 'v*.*.*'
  # 手动触发：允许用户指定tag
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., v1.0.0-alpha)'
        required: true
        default: 'latest'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 设置tag变量，根据触发方式不同而变化
      - name: Set Tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            infq/plugin:${{ env.TAG }},
            infq/plugin:latest